### ISSUE TITLE
Figure out the ^^ situation

### ISSUE THREAD

**Issue by jamespfennell** [jamespfennell/texcraft#4]
In TeX you can write `^^A`, and this somehow means the character `('A' as usize+128)%256`. TeX by topic mentions this in the context of the lexer, so maybe this logic lives in the lexer. Anyway, need to figure it out.

**Comment by jamespfennell** [comment]
The good news is that the `^^` construction lives entirely in the lexer. I discovered this by finding and reading the TeX lexer code - it's sections 344 through 356 in my edition of the TeXBook.

The `^^` construction is also legal in control sequence names.

I'm not 100% sure, but I don't think different characters with the superscript category can be used together. E.g., if both `^` and `_` have category code superscript, you can do `^^` or `__` but I don't think you can do `^_`. This is because the TeX code checking for this seems to compare the character value only. Should double check pdfTeX.

Another thing I learned while reading the lexer code is that all space tokens get the ` ` character! This has implications for pattern matching in user defined macros. Need to fix this and add a unit test in the `\def` package for this.

Finally while auditing the lexer we should double check the situation with `\par` and write a unit test.

**Comment by jx2518** [comment]
Hi, I raised a question in your other repo realtimerail.nyc-react 10 days ago. Maybe it's an old repo that you are not working on anymore, so you haven't gotten chance to looked at my question. Could you please go check it out and see if you could help? Thanks a lot.
